-- =============================================================================
-- Quantum Workforce OS (QWOS)
-- QuantumDB
-- =============================================================================
--
-- File        : 067_leave_approval_notifications.sql
-- Version     : 1.0
-- Description : Leave approval notification records
--
-- =============================================================================
--
-- Purpose
-- -----------------------------------------------------------------------------
-- Records notifications generated by the leave approval workflow.
--
-- This table stores the notification EVENT and its delivery state.
-- It does not store the actual email/message body as the source of truth.
--
-- Typical events:
--
--   approval_required
--   approval_approved
--   approval_rejected
--   approval_escalated
--   approval_delegated
--   leave_submitted
--   leave_withdrawn
--   leave_cancelled
--
-- Workflow configuration:
--
--   063 leave_approval_workflows
--   064 leave_approval_workflow_steps
--   065 leave_approval_delegations
--   066 leave_approval_escalations
--
-- Runtime approval:
--
--   042 leave_request_approvals
--
-- Runtime status:
--
--   062 leave_request_status_history
--
-- =============================================================================

BEGIN;

-- =============================================================================
-- LEAVE APPROVAL NOTIFICATIONS
-- =============================================================================

CREATE TABLE leave_approval_notifications (

    ---------------------------------------------------------------------------
    -- Primary Key
    ---------------------------------------------------------------------------

    id CHAR(26) PRIMARY KEY,

    ---------------------------------------------------------------------------
    -- Tenant
    ---------------------------------------------------------------------------

    tenant_id CHAR(26) NOT NULL,

    ---------------------------------------------------------------------------
    -- Leave Request
    ---------------------------------------------------------------------------

    leave_request_id CHAR(26) NOT NULL,

    ---------------------------------------------------------------------------
    -- Optional Approval Record
    ---------------------------------------------------------------------------

    leave_request_approval_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Optional Workflow
    ---------------------------------------------------------------------------

    leave_approval_workflow_id CHAR(26),

    leave_approval_workflow_step_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Optional Escalation
    ---------------------------------------------------------------------------

    leave_approval_escalation_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Recipient
    ---------------------------------------------------------------------------

    recipient_employee_id CHAR(26) NOT NULL,

    ---------------------------------------------------------------------------
    -- Notification Identification
    ---------------------------------------------------------------------------

    notification_number VARCHAR(50) NOT NULL,

    ---------------------------------------------------------------------------
    -- Notification Event
    --
    -- approval_required
    -- approval_approved
    -- approval_rejected
    -- approval_escalated
    -- approval_delegated
    -- leave_submitted
    -- leave_withdrawn
    -- leave_cancelled
    ---------------------------------------------------------------------------

    notification_type identifier_code NOT NULL,

    ---------------------------------------------------------------------------
    -- Delivery Channel
    --
    -- email
    -- in_app
    -- push
    -- sms
    ---------------------------------------------------------------------------

    delivery_channel identifier_code NOT NULL DEFAULT 'in_app',

    ---------------------------------------------------------------------------
    -- Notification Content Reference
    ---------------------------------------------------------------------------

    subject VARCHAR(255),

    message TEXT,

    ---------------------------------------------------------------------------
    -- Delivery Status
    --
    -- pending
    -- queued
    -- sent
    -- delivered
    -- read
    -- failed
    -- cancelled
    ---------------------------------------------------------------------------

    status identifier_code NOT NULL DEFAULT 'pending',

    ---------------------------------------------------------------------------
    -- Delivery Timing
    ---------------------------------------------------------------------------

    scheduled_at TIMESTAMPTZ,

    sent_at TIMESTAMPTZ,

    delivered_at TIMESTAMPTZ,

    read_at TIMESTAMPTZ,

    ---------------------------------------------------------------------------
    -- Failure Information
    ---------------------------------------------------------------------------

    failure_reason TEXT,

    delivery_attempts INTEGER NOT NULL DEFAULT 0,

    ---------------------------------------------------------------------------
    -- Lifecycle
    ---------------------------------------------------------------------------

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    ---------------------------------------------------------------------------
    -- Audit
    ---------------------------------------------------------------------------

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by CHAR(26),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_by CHAR(26),

    deleted_at TIMESTAMPTZ,

    deleted_by CHAR(26),

    ---------------------------------------------------------------------------
    -- Concurrency
    ---------------------------------------------------------------------------

    version INTEGER NOT NULL DEFAULT 1,

    ---------------------------------------------------------------------------
    -- Foreign Keys
    ---------------------------------------------------------------------------

    CONSTRAINT fk_leave_approval_notifications_request
        FOREIGN KEY (leave_request_id)
        REFERENCES leave_requests(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notifications_approval
        FOREIGN KEY (leave_request_approval_id)
        REFERENCES leave_request_approvals(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notifications_workflow
        FOREIGN KEY (leave_approval_workflow_id)
        REFERENCES leave_approval_workflows(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notifications_workflow_step
        FOREIGN KEY (leave_approval_workflow_step_id)
        REFERENCES leave_approval_workflow_steps(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notifications_escalation
        FOREIGN KEY (leave_approval_escalation_id)
        REFERENCES leave_approval_escalations(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notifications_recipient
        FOREIGN KEY (recipient_employee_id)
        REFERENCES employees(id)
        ON DELETE RESTRICT,

    ---------------------------------------------------------------------------
    -- Notification Number
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_number
        CHECK (
            LENGTH(TRIM(notification_number)) > 0
        ),

    ---------------------------------------------------------------------------
    -- Notification Type
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_type
        CHECK (
            notification_type IN (
                'approval_required',
                'approval_approved',
                'approval_rejected',
                'approval_escalated',
                'approval_delegated',
                'leave_submitted',
                'leave_withdrawn',
                'leave_cancelled'
            )
        ),

    ---------------------------------------------------------------------------
    -- Delivery Channel
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_channel
        CHECK (
            delivery_channel IN (
                'email',
                'in_app',
                'push',
                'sms'
            )
        ),

    ---------------------------------------------------------------------------
    -- Delivery Status
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_status
        CHECK (
            status IN (
                'pending',
                'queued',
                'sent',
                'delivered',
                'read',
                'failed',
                'cancelled'
            )
        ),

    ---------------------------------------------------------------------------
    -- Delivery Attempts
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_attempts
        CHECK (
            delivery_attempts >= 0
        ),

    ---------------------------------------------------------------------------
    -- Sent Timestamp
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_sent
        CHECK (
            sent_at IS NULL
            OR sent_at >= created_at
        ),

    ---------------------------------------------------------------------------
    -- Delivered Timestamp
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_delivered
        CHECK (
            delivered_at IS NULL
            OR (
                sent_at IS NOT NULL
                AND delivered_at >= sent_at
            )
        ),

    ---------------------------------------------------------------------------
    -- Read Timestamp
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_read
        CHECK (
            read_at IS NULL
            OR (
                delivered_at IS NOT NULL
                AND read_at >= delivered_at
            )
        ),

    ---------------------------------------------------------------------------
    -- Failure Consistency
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notifications_failure
        CHECK (
            (
                status <> 'failed'
                AND failure_reason IS NULL
            )
            OR
            (
                status = 'failed'
                AND failure_reason IS NOT NULL
                AND LENGTH(TRIM(failure_reason)) > 0
            )
        )

);

-- =============================================================================
-- UNIQUE CONSTRAINTS
-- =============================================================================

CREATE UNIQUE INDEX uq_leave_approval_notifications_number
    ON leave_approval_notifications(
        tenant_id,
        notification_number
    );

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_leave_approval_notifications_request
    ON leave_approval_notifications(
        tenant_id,
        leave_request_id
    );

CREATE INDEX idx_leave_approval_notifications_approval
    ON leave_approval_notifications(
        leave_request_approval_id
    );

CREATE INDEX idx_leave_approval_notifications_workflow
    ON leave_approval_notifications(
        tenant_id,
        leave_approval_workflow_id
    );

CREATE INDEX idx_leave_approval_notifications_workflow_step
    ON leave_approval_notifications(
        tenant_id,
        leave_approval_workflow_step_id
    );

CREATE INDEX idx_leave_approval_notifications_escalation
    ON leave_approval_notifications(
        leave_approval_escalation_id
    );

CREATE INDEX idx_leave_approval_notifications_recipient
    ON leave_approval_notifications(
        tenant_id,
        recipient_employee_id
    );

CREATE INDEX idx_leave_approval_notifications_type
    ON leave_approval_notifications(
        tenant_id,
        notification_type
    );

CREATE INDEX idx_leave_approval_notifications_status
    ON leave_approval_notifications(
        tenant_id,
        status
    );

CREATE INDEX idx_leave_approval_notifications_scheduled
    ON leave_approval_notifications(
        tenant_id,
        scheduled_at
    );

CREATE INDEX idx_leave_approval_notifications_pending
    ON leave_approval_notifications(
        tenant_id,
        status,
        scheduled_at
    )
    WHERE status IN ('pending', 'queued');

CREATE INDEX idx_leave_approval_notifications_active
    ON leave_approval_notifications(
        tenant_id,
        is_active
    );

COMMIT;