-- =============================================================================
-- Quantum Workforce OS (QWOS)
-- QuantumDB
-- =============================================================================
--
-- File        : 072_leave_approval_notification_events.sql
-- Version     : 1.0
-- Description : Leave approval notification event / outbox records
--
-- =============================================================================
--
-- Purpose
-- -----------------------------------------------------------------------------
-- Stores notification events generated by leave workflow actions before they
-- are processed by the notification service.
--
-- 067_leave_approval_notifications
--     = Notification record / rendered notification snapshot
--
-- 068_leave_approval_notification_preferences
--     = Employee delivery preferences
--
-- 069_leave_approval_notification_templates
--     = Reusable notification templates
--
-- 070_leave_approval_notification_template_variables
--     = Controlled template variable registry
--
-- 071_leave_approval_notification_delivery_logs
--     = Individual delivery attempts
--
-- 072_leave_approval_notification_events
--     = Durable event / outbox record that triggers notification processing
--
-- The event record is intentionally separate from the notification record.
-- This allows leave workflow transactions to create a durable event without
-- coupling the workflow transaction directly to an external delivery provider.
--
-- =============================================================================

BEGIN;

-- =============================================================================
-- LEAVE APPROVAL NOTIFICATION EVENTS
-- =============================================================================

CREATE TABLE leave_approval_notification_events (

    ---------------------------------------------------------------------------
    -- Primary Key
    ---------------------------------------------------------------------------

    id CHAR(26) PRIMARY KEY,

    ---------------------------------------------------------------------------
    -- Tenant
    ---------------------------------------------------------------------------

    tenant_id CHAR(26) NOT NULL,

    ---------------------------------------------------------------------------
    -- Event Identification
    ---------------------------------------------------------------------------

    event_number VARCHAR(50) NOT NULL,

    event_type identifier_code NOT NULL,

    ---------------------------------------------------------------------------
    -- Leave Request
    ---------------------------------------------------------------------------

    leave_request_id CHAR(26) NOT NULL,

    ---------------------------------------------------------------------------
    -- Optional Approval Context
    ---------------------------------------------------------------------------

    leave_request_approval_id CHAR(26),

    leave_approval_workflow_id CHAR(26),

    leave_approval_workflow_step_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Recipient
    --
    -- The notification service may later resolve multiple recipients.
    -- When known at event creation time, the intended recipient can be stored
    -- here.
    ---------------------------------------------------------------------------

    recipient_employee_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Source Business Event
    --
    -- source_id is intentionally not an FK because the source may belong to
    -- different business-event tables.
    ---------------------------------------------------------------------------

    source_type identifier_code,

    source_id CHAR(26),

    ---------------------------------------------------------------------------
    -- Event Payload
    --
    -- Stores event-specific metadata required by the notification processor.
    -- The application controls the JSON structure.
    ---------------------------------------------------------------------------

    event_payload JSONB,

    ---------------------------------------------------------------------------
    -- Processing
    --
    -- pending
    -- processing
    -- processed
    -- failed
    -- cancelled
    ---------------------------------------------------------------------------

    status identifier_code NOT NULL DEFAULT 'pending',

    attempt_count INTEGER NOT NULL DEFAULT 0,

    max_attempts INTEGER NOT NULL DEFAULT 5,

    ---------------------------------------------------------------------------
    -- Processing Timestamps
    ---------------------------------------------------------------------------

    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    processing_started_at TIMESTAMPTZ,

    processed_at TIMESTAMPTZ,

    failed_at TIMESTAMPTZ,

    ---------------------------------------------------------------------------
    -- Retry
    ---------------------------------------------------------------------------

    next_attempt_at TIMESTAMPTZ,

    ---------------------------------------------------------------------------
    -- Error Information
    ---------------------------------------------------------------------------

    error_code VARCHAR(100),

    error_message TEXT,

    ---------------------------------------------------------------------------
    -- Correlation / Trace
    ---------------------------------------------------------------------------

    correlation_id VARCHAR(100),

    causation_id VARCHAR(100),

    ---------------------------------------------------------------------------
    -- Lifecycle
    ---------------------------------------------------------------------------

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    ---------------------------------------------------------------------------
    -- Audit
    ---------------------------------------------------------------------------

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by CHAR(26),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_by CHAR(26),

    deleted_at TIMESTAMPTZ,

    deleted_by CHAR(26),

    ---------------------------------------------------------------------------
    -- Concurrency
    ---------------------------------------------------------------------------

    version INTEGER NOT NULL DEFAULT 1,

    ---------------------------------------------------------------------------
    -- Foreign Keys
    ---------------------------------------------------------------------------

    CONSTRAINT fk_leave_approval_notification_events_request
        FOREIGN KEY (leave_request_id)
        REFERENCES leave_requests(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notification_events_approval
        FOREIGN KEY (leave_request_approval_id)
        REFERENCES leave_request_approvals(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notification_events_workflow
        FOREIGN KEY (leave_approval_workflow_id)
        REFERENCES leave_approval_workflows(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notification_events_workflow_step
        FOREIGN KEY (leave_approval_workflow_step_id)
        REFERENCES leave_approval_workflow_steps(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approval_notification_events_recipient
        FOREIGN KEY (recipient_employee_id)
        REFERENCES employees(id)
        ON DELETE RESTRICT,

    ---------------------------------------------------------------------------
    -- Event Number
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_number
        CHECK (
            BTRIM(event_number) <> ''
        ),

    ---------------------------------------------------------------------------
    -- Event Type
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_type
        CHECK (
            event_type IN (
                'approval_required',
                'approval_approved',
                'approval_rejected',
                'approval_escalated',
                'approval_delegated',
                'leave_submitted',
                'leave_withdrawn',
                'leave_cancelled'
            )
        ),

    ---------------------------------------------------------------------------
    -- Source
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_source
        CHECK (
            (
                source_type IS NULL
                AND source_id IS NULL
            )
            OR
            (
                source_type IS NOT NULL
                AND source_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_leave_approval_notification_events_source_type
        CHECK (
            source_type IS NULL
            OR source_type IN (
                'leave_request',
                'leave_approval',
                'leave_delegation',
                'leave_escalation',
                'leave_cancellation',
                'leave_withdrawal',
                'system'
            )
        ),

    ---------------------------------------------------------------------------
    -- Status
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_status
        CHECK (
            status IN (
                'pending',
                'processing',
                'processed',
                'failed',
                'cancelled'
            )
        ),

    ---------------------------------------------------------------------------
    -- Attempts
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_attempts
        CHECK (
            attempt_count >= 0
            AND max_attempts > 0
            AND attempt_count <= max_attempts
        ),

    ---------------------------------------------------------------------------
    -- Processing Timestamps
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_processing_timestamps
        CHECK (
            processing_started_at IS NULL
            OR processing_started_at >= occurred_at
        ),

    CONSTRAINT chk_leave_approval_notification_events_processed_timestamp
        CHECK (
            processed_at IS NULL
            OR (
                processing_started_at IS NOT NULL
                AND processed_at >= processing_started_at
            )
        ),

    CONSTRAINT chk_leave_approval_notification_events_failed_timestamp
        CHECK (
            failed_at IS NULL
            OR (
                processing_started_at IS NOT NULL
                AND failed_at >= processing_started_at
            )
        ),

    ---------------------------------------------------------------------------
    -- Retry
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_retry
        CHECK (
            next_attempt_at IS NULL
            OR (
                status = 'failed'
                AND next_attempt_at > occurred_at
            )
        ),

    ---------------------------------------------------------------------------
    -- Error
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_error
        CHECK (
            status <> 'failed'
            OR (
                failed_at IS NOT NULL
                AND (
                    error_code IS NOT NULL
                    OR error_message IS NOT NULL
                )
            )
        ),

    ---------------------------------------------------------------------------
    -- Status / Timestamp Consistency
    ---------------------------------------------------------------------------

    CONSTRAINT chk_leave_approval_notification_events_status_consistency
        CHECK (
            (
                status <> 'processing'
                OR processing_started_at IS NOT NULL
            )
            AND
            (
                status <> 'processed'
                OR processed_at IS NOT NULL
            )
            AND
            (
                status <> 'failed'
                OR failed_at IS NOT NULL
            )
        )

);

-- =============================================================================
-- UNIQUE EVENT NUMBER
-- =============================================================================

CREATE UNIQUE INDEX uq_leave_approval_notification_events_number
    ON leave_approval_notification_events(
        tenant_id,
        event_number
    );

-- =============================================================================
-- IDEMPOTENCY / SOURCE INDEX
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_source
    ON leave_approval_notification_events(
        tenant_id,
        source_type,
        source_id
    );

-- =============================================================================
-- LEAVE REQUEST
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_request
    ON leave_approval_notification_events(
        tenant_id,
        leave_request_id
    );

-- =============================================================================
-- APPROVAL
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_approval
    ON leave_approval_notification_events(
        tenant_id,
        leave_request_approval_id
    );

-- =============================================================================
-- WORKFLOW
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_workflow
    ON leave_approval_notification_events(
        tenant_id,
        leave_approval_workflow_id,
        leave_approval_workflow_step_id
    );

-- =============================================================================
-- RECIPIENT
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_recipient
    ON leave_approval_notification_events(
        tenant_id,
        recipient_employee_id
    );

-- =============================================================================
-- EVENT TYPE
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_type
    ON leave_approval_notification_events(
        tenant_id,
        event_type
    );

-- =============================================================================
-- STATUS
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_status
    ON leave_approval_notification_events(
        tenant_id,
        status
    );

-- =============================================================================
-- EVENT OCCURRENCE
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_occurred
    ON leave_approval_notification_events(
        tenant_id,
        occurred_at
    );

-- =============================================================================
-- PROCESSING QUEUE
-- =============================================================================
--
-- Optimized for workers looking for events that are ready to process.
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_pending
    ON leave_approval_notification_events(
        tenant_id,
        available_at,
        occurred_at
    )
    WHERE status = 'pending'
      AND is_active = TRUE;

-- =============================================================================
-- RETRY QUEUE
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_retry
    ON leave_approval_notification_events(
        tenant_id,
        next_attempt_at
    )
    WHERE status = 'failed'
      AND next_attempt_at IS NOT NULL
      AND is_active = TRUE;

-- =============================================================================
-- ACTIVE EVENTS
-- =============================================================================

CREATE INDEX idx_leave_approval_notification_events_active
    ON leave_approval_notification_events(
        tenant_id,
        is_active
    );

COMMIT;