"""
===============================================================================
Quantum Workforce OS (QWOS)

Infrastructure Layer

SHA-256 Token Hasher

Description:
    Provides deterministic hashing for high-entropy authentication tokens.

Responsibilities:
    - Hash refresh tokens before persistence
    - Verify raw tokens against persisted hashes
    - Never persist raw refresh tokens

Author:
    Richard Balabarcon
===============================================================================
"""

from __future__ import annotations

import hashlib
import hmac

from qwos.application.common.ports.token_hasher import TokenHasher


class SHA256TokenHasher(TokenHasher):
    """
    SHA-256 implementation of the TokenHasher contract.

    Refresh tokens are high-entropy secrets generated by the token provider.
    A deterministic SHA-256 digest allows the application to look up and
    verify persisted refresh tokens without storing the raw token.
    """

    def hash(
        self,
        token: str,
    ) -> str:
        """
        Return the SHA-256 hexadecimal digest of a token.
        """

        return hashlib.sha256(
            token.encode("utf-8"),
        ).hexdigest()

    def verify(
        self,
        token: str,
        token_hash: str,
    ) -> bool:
        """
        Verify a raw token against its persisted SHA-256 hash.

        Constant-time comparison is used to avoid leaking comparison timing.
        """

        calculated_hash = self.hash(token)

        return hmac.compare_digest(
            calculated_hash,
            token_hash,
        )